[workspace]
members = ["crates/clap-tui", "crates/clap-tui-macros"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
ratatui = "0.28"
crossterm = "0.27"
thiserror = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
