[package]
name = "clap-tui"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Auto-generate a TUI from clap commands"
readme = "../../README.md"
repository = "https://github.com/gitseti/clap-tui"
homepage = "https://github.com/gitseti/clap-tui"
documentation = "https://docs.rs/clap-tui"
keywords = ["clap", "tui", "terminal", "cli", "ratatui"]
categories = ["command-line-interface", "development-tools"]

[package.metadata.release]
tag-name = "v{{version}}"

[features]
default = ["mouse"]
mouse = []

[dependencies]
clap.workspace = true
ratatui.workspace = true
crossterm.workspace = true
thiserror.workspace = true
ratatui-textarea = { version = "0.9", default-features = false }
arboard = "3.6.1"
