[package]
name = "clap-tui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Auto-generate a TUI from clap commands"

[features]
default = ["mouse"]
mouse = []
tracing = ["dep:tracing"]

[dependencies]
clap.workspace = true
ratatui.workspace = true
crossterm.workspace = true
thiserror.workspace = true
clap-tui-macros = { path = "../clap-tui-macros" }
tracing = { version = "0.1", optional = true }
tui-textarea = "0.4"
arboard = "3.6.1"

[dev-dependencies]
trybuild = "1"
